device: 0
calibration:
  lidar_to_camera:
    xyz: [0,0,0]
    orientation: [0,0,0,1]
tracker:
  frame_synthesis:
    strategy: NULL
    sky_removal: NULL
    frame_decimation_rate_hz: 10
  icp:
    threshold: 2.2
    max_iterations: 18
    relative_fitness: 1.e-10
    relative_rmse: 1.e-10
    downsample:
      type: UNIFORM
      target_uniform_point_count: 10000
      voxel_downsample_size: 0.1
mapper:
  keyframe_manager:
    key_frame_selection:
      strategy: TEMPORAL
      temporal:
        time_diff_seconds: 1
    window_selection:
      strategy: MOST_RECENT
      window_size: 10
    sample_allocation:
      strategy: UNIFORM

      # How many samples to take uniformly across non-sky regions
      num_samples_uniform: 200
      
      # How many to use strategy to choose. This is an average since it may vary by image. 
      avg_num_samples_from_strategy: 200 
      
      # How many samples to take from sky region (uniformly)
      num_sky_samples: 50
      
  optimizer: NULL
