# This is mainly used for testing purposes and to show structure
# - but should be overwritten  at runtime by reading data logs,
# camera info messages, etc.
calibration:
  lidar_to_camera:
    xyz: [0,0,0]
    orientation: [0,0,0,1] 
  camera_intrinsic:
    k: NULL
    distortion: NULL
    new_k: NULL
    width: NULL
    height: NULL

debug:
  global_enabled: True
  flags:
    pytorch_detect_anomaly: False
    draw_comp_graph: False
    write_ray_point_clouds: False
    write_icp_point_clouds: False
    profile: False

# ros_names:
#   camera: "ego_vehicle/rgb_front"
#   lidar: "ego_vehicle/lidar"
#   camera_suffix: "image"
#   topic_prefix: "/carla"
ros_names:
  camera: "stereo/frame_left"
  lidar: "os_cloud_node/points"
  camera_suffix: "image_raw/compressed"
  topic_prefix: "/"
  
tracker:
  frame_synthesis:
    strategy: NULL
    sky_removal: NULL
    frame_decimation_rate_hz: 10
  icp:
    threshold: 0.125
    max_iterations: 20
    relative_fitness: 1.e-10
    relative_rmse: 1.e-10
    downsample:
      type: UNIFORM
      target_uniform_point_count: 10000
      voxel_downsample_size: 0.1
mapper:
  device: 0
  keyframe_manager:
    keyframe_selection:
      strategy: TEMPORAL
      temporal:
        time_diff_seconds: 1
    window_selection:
      strategy: MOST_RECENT
      window_size: 10
    sample_allocation:
      strategy: UNIFORM

      # How many samples to take uniformly across non-sky regions. 
      # Remember 2 images per frame, so this is doubled.
      num_rgb_uniform_samples: 1024
      
      # How many to use strategy to choose. This is an average since it may vary by image. 
      avg_rgb_strategy_samples: 256

      # Same, for lidar
      num_lidar_uniform_samples: 1024
      avg_lidar_strategy_samples: 256
      
      # How many samples to take from sky region (uniformly)
      num_sky_samples: 50

  optimizer:
    enabled: True
    default_optimizer_settings:
      stage: 3
      num_iterations: 1500
      fix_poses: True
      fix_sigma_mlp: False
      fix_rgb_mlp: False
    sample_strategy: UNIFORM
    iteration_schedule:
      - 
        num_keyframes: 1
        iteration_count: 1500
      -
        num_keyframes: -1
        iteration_count: 60

    model_config: !include model_config/decoupled_carla_halfres.yaml
  