calibration:
  lidar_to_camera:
    xyz: [0,0,0]
    orientation: [0,0,0,1]
tracker:
  frame_synthesis:
    strategy: NULL
    sky_removal: NULL
    frame_decimation_rate_hz: 10
  icp:
    threshold: 1.0
    max_iterations: 10
    relative_fitness: 1.e-5
    relative_rmse: 1.e-5
mapper:
  keyframe_manager:
    key_frame_strategy: NULL
    window_selection_strategy: NULL
    sample_allocation_strategy: NULL
  optimizer: NULL
